# Generated by Django 4.2.3 on 2023-07-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Women',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('coutent', models.TextField()),
                ('photo', models.ImageField(upload_to='images')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
