# Generated by Django 4.2.3 on 2023-07-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='women',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
